# Generated by Django 3.1.6 on 2022-05-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_merge_20190815_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='numero',
            field=models.CharField(max_length=5, verbose_name='Número'),
        ),
    ]
