# Generated by Django 4.0.1 on 2022-04-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='qtd_total',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
